spring:
  config.activate.on-profile: test
  test:
    database:
      replace: NONE
  liquibase:
    contexts: test
  datasource:
    url: jdbc:tc:postgresql:16:///db?TC_TMPFS=/testtmpfs:rw
    hikari:
      register-mbeans: true
      autoCommit: false
      maximum-pool-size: 2
  jpa:
    properties:
      hibernate:
        show-sql: false
        query:
          plan_cache_max_size: 4096
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 40
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 200
        # Need for BLOB: hibernateFactory.getCurrentSession()
        current_session_context_class: thread
    hibernate:
      ddl-auto: validate
      naming:
        # Embeddable are using field prefix for column naming
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

logging:
  level:
    root: info
    org.testcontainers.utility.RyukResourceReaper: error
    #    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: info
    org.hibernate.SQL: debug