spring:
  config.activate.on-profile: test
  test:
    database:
      replace: NONE
  liquibase:
    contexts: test
  datasource:
    url: jdbc:tc:postgresql:16:///db?TC_TMPFS=/testtmpfs:rw
    hikari:
      register-mbeans: true
      autoCommit: false
      maximum-pool-size: 2
  jpa:
    properties:
      hibernate:
        show-sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 40
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info
    org.testcontainers.utility.RyukResourceReaper: error
    #    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: info
    org.hibernate.SQL: debug